-- MySQL Script generated by MySQL Workbench
-- 11/16/16 18:09:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`planos_de_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planos_de_saude` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_plano` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `portador_de_deficiencia` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '',
  `data_de_nascimento` DATE NULL COMMENT '',
  `telefone` INT UNSIGNED NULL COMMENT '',
  `privilegio` INT DEFAULT 0 COMMENT '',
  `endereco` VARCHAR(90) NULL COMMENT '',
  `senha` VARCHAR(45) NOT NULL COMMENT '',
   `id_plano` INT UNSIGNED NOT NULL COMMENT '',
  `username` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '	',
  `CRM` INT UNSIGNED NOT NULL COMMENT '',
  `especialidade` VARCHAR(45) NOT NULL COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `telefone` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `id_consulta` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_usuario` INT UNSIGNED NOT NULL COMMENT '',
  `id_medico` INT UNSIGNED NOT NULL COMMENT '',
  `dia` DATE NOT NULL COMMENT '',
  `horario_inicio` TIME NOT NULL COMMENT '',
  `horario_termino` TIME NOT NULL COMMENT '',
  PRIMARY KEY (`id_consulta`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospitais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospitais` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome` VARCHAR(45) NOT NULL COMMENT '',
  `endereco` VARCHAR(90) NOT NULL COMMENT '',
  `telefone` VARCHAR(12) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tempo_de_espera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tempo_de_espera` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_hospital` INT UNSIGNED NOT NULL COMMENT '',
  `manha` INT UNSIGNED NULL COMMENT '',
  `tarde` INT UNSIGNED NULL COMMENT '',
  `noite` INT UNSIGNED NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT ''
  )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico_trabalha_em_hosp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico_trabalha_em_hosp` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `id_hospital` INT UNSIGNED NOT NULL COMMENT '',
  `id_medico` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`planos_de_saude_has_hospitais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planos_de_saude_has_hospitais` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `planos_de_saude_id` INT UNSIGNED NOT NULL COMMENT '',
  `hospitais_id` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
