-- MySQL Script generated by MySQL Workbench
-- Thu Nov 10 19:56:17 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`hospitais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospitais` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hospital_aceita_plano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hospital_aceita_plano` (
  `id_hospital` INT UNSIGNED NOT NULL,
  `id_plano` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_hospital`),
  CONSTRAINT `fk_hospital_aceita_plano_hospitais1`
    FOREIGN KEY (`id_hospital`)
    REFERENCES `mydb`.`hospitais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`planos_de_saude`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`planos_de_saude` (
  `id` INT UNSIGNED NOT NULL,
  `nome_plano` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_planos_de_saude_plano_de_saude_e_hospitais1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`hospital_aceita_plano` (`id_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `plano_de_saude` VARCHAR(45) NOT NULL,
  `portador_de_deficiencia` TINYINT(1) NOT NULL DEFAULT 0,
  `data_de_nascimento` DATE NULL,
  `telefone` INT UNSIGNED NULL,
  `endereco` VARCHAR(90) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_planos_de_saude1_idx` (`plano_de_saude` ASC),
  CONSTRAINT `fk_usuario_planos_de_saude1`
    FOREIGN KEY (`plano_de_saude`)
    REFERENCES `mydb`.`planos_de_saude` (`nome_plano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '	',
  `CRM` INT UNSIGNED NOT NULL,
  `especialidade` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consulta` (
  `id_consulta` INT UNSIGNED NOT NULL,
  `id_usuario` INT UNSIGNED NOT NULL,
  `id_medico` INT UNSIGNED NOT NULL,
  `dia` DATE NOT NULL,
  `horario_inicio` TIME NOT NULL,
  `horario_termino` TIME NOT NULL,
  INDEX `fk_consulta_medico1_idx` (`id_medico` ASC),
  PRIMARY KEY (`id_consulta`),
  CONSTRAINT `fk_consulta_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_medico1`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mydb`.`medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tempo_de_espera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tempo_de_espera` (
  `id_hospital` INT UNSIGNED NOT NULL,
  `manha` INT UNSIGNED NULL,
  `tarde` INT UNSIGNED NULL,
  `noite` INT UNSIGNED NULL,
  PRIMARY KEY (`id_hospital`),
  CONSTRAINT `fk_tempo_de_espera_hospitais1`
    FOREIGN KEY (`id_hospital`)
    REFERENCES `mydb`.`hospitais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medico_trabalha_em_hosp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`medico_trabalha_em_hosp` (
  `id_hospital` INT NOT NULL,
  `id_medico` INT UNSIGNED NOT NULL,
  INDEX `fk_medico_has_hospitais_hospitais1_idx` (`id_hospital` ASC),
  INDEX `fk_medico_has_hospitais_medico1_idx` (`id_medico` ASC),
  PRIMARY KEY (`id_hospital`),
  CONSTRAINT `fk_medico_has_hospitais_medico1`
    FOREIGN KEY (`id_medico`)
    REFERENCES `mydb`.`medico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medico_has_hospitais_hospitais1`
    FOREIGN KEY (`id_hospital`)
    REFERENCES `mydb`.`hospitais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
